import type { BrandScoreResult } from "@/lib/services/interfaces";

export interface DemoName {
  name: string;
  tagline: string;
  reasoning: string;
  brandScore: BrandScoreResult;
  domains: { domain: string; tld: string; available?: boolean; checkedAgo?: string }[];
}

export interface DemoJourney {
  id: string;
  input: string;
  label: string;
  names: DemoName[];
}

export const DEMO_JOURNEYS: DemoJourney[] = [
  {
    id: "ai-scheduling",
    input: "AI scheduling tool for consultants",
    label: "AI Scheduling Tool",
    names: [
      {
        name: "Caligo",
        tagline: "Your calendar, finally intelligent",
        reasoning: "Blend of 'calendar' and 'go' — short, punchy, and implies smart scheduling on the move.",
        brandScore: {
          overall: 88,
          breakdown: { memorability: 92, pronounceability: 90, uniqueness: 85, relevance: 82, length: 91 },
          summary: "Highly memorable with a modern, tech-forward feel. Easy to spell and say.",
        },
        domains: [
          { domain: "caligo.com", tld: ".com", available: false, checkedAgo: "2m ago" },
          { domain: "caligo.net", tld: ".net", available: false, checkedAgo: "5m ago" },
          { domain: "caligo.app", tld: ".app", available: true, checkedAgo: "12m ago" },
          { domain: "caligo.dev", tld: ".dev", available: true, checkedAgo: "1h ago" },
          { domain: "caligo.io", tld: ".io" },
          { domain: "caligo.ai", tld: ".ai" },
          { domain: "caligo.co", tld: ".co" },
        ],
      },
      {
        name: "Slotwise",
        tagline: "Smarter time, better meetings",
        reasoning: "Combines 'slot' (time slot) with 'wise' — communicates intelligent scheduling clearly.",
        brandScore: {
          overall: 82,
          breakdown: { memorability: 80, pronounceability: 95, uniqueness: 72, relevance: 90, length: 78 },
          summary: "Descriptive and instantly clear. Slightly generic but very approachable.",
        },
        domains: [
          { domain: "slotwise.com", tld: ".com", available: true, checkedAgo: "3h ago" },
          { domain: "slotwise.net", tld: ".net", available: true, checkedAgo: "6h ago" },
          { domain: "slotwise.app", tld: ".app", available: true, checkedAgo: "1d ago" },
          { domain: "slotwise.dev", tld: ".dev", available: true, checkedAgo: "2d ago" },
          { domain: "slotwise.io", tld: ".io" },
          { domain: "slotwise.ai", tld: ".ai" },
          { domain: "slotwise.co", tld: ".co" },
        ],
      },
      {
        name: "Calendex",
        tagline: "Index your time. Optimize your day.",
        reasoning: "Portmanteau of 'calendar' and 'index' — suggests organized, data-driven scheduling.",
        brandScore: {
          overall: 85,
          breakdown: { memorability: 86, pronounceability: 88, uniqueness: 80, relevance: 88, length: 84 },
          summary: "Strong brand potential with clear category association. Professional tone.",
        },
        domains: [
          { domain: "calendex.com", tld: ".com", available: false, checkedAgo: "2m ago" },
          { domain: "calendex.net", tld: ".net", available: true, checkedAgo: "5m ago" },
          { domain: "calendex.app", tld: ".app", available: true, checkedAgo: "12m ago" },
          { domain: "calendex.dev", tld: ".dev", available: true, checkedAgo: "1h ago" },
          { domain: "calendex.io", tld: ".io" },
          { domain: "calendex.ai", tld: ".ai" },
          { domain: "calendex.co", tld: ".co" },
        ],
      },
      {
        name: "Meetra",
        tagline: "Meetings that respect your time",
        reasoning: "Derived from 'meet' with a modern suffix — sounds warm, human, and approachable.",
        brandScore: {
          overall: 79,
          breakdown: { memorability: 82, pronounceability: 86, uniqueness: 74, relevance: 76, length: 88 },
          summary: "Friendly and easy to remember. May need strong branding to stand out.",
        },
        domains: [
          { domain: "meetra.com", tld: ".com", available: true, checkedAgo: "3h ago" },
          { domain: "meetra.net", tld: ".net", available: true, checkedAgo: "6h ago" },
          { domain: "meetra.app", tld: ".app", available: true, checkedAgo: "1d ago" },
          { domain: "meetra.dev", tld: ".dev", available: true, checkedAgo: "2d ago" },
          { domain: "meetra.io", tld: ".io" },
          { domain: "meetra.ai", tld: ".ai" },
          { domain: "meetra.co", tld: ".co" },
        ],
      },
      {
        name: "Chronofit",
        tagline: "Fit more into every day",
        reasoning: "Greek 'chronos' (time) + 'fit' — implies optimizing time to fit everything in.",
        brandScore: {
          overall: 76,
          breakdown: { memorability: 78, pronounceability: 72, uniqueness: 82, relevance: 74, length: 74 },
          summary: "Unique and distinctive, but slightly harder to spell. Strong for a niche audience.",
        },
        domains: [
          { domain: "chronofit.com", tld: ".com", available: true, checkedAgo: "2m ago" },
          { domain: "chronofit.net", tld: ".net", available: true, checkedAgo: "5m ago" },
          { domain: "chronofit.app", tld: ".app", available: true, checkedAgo: "12m ago" },
          { domain: "chronofit.dev", tld: ".dev", available: true, checkedAgo: "1h ago" },
          { domain: "chronofit.io", tld: ".io" },
          { domain: "chronofit.ai", tld: ".ai" },
          { domain: "chronofit.co", tld: ".co" },
        ],
      },
    ],
  },
  {
    id: "expense-tracker",
    input: "Expense tracker for freelancers",
    label: "Expense Tracker",
    names: [
      {
        name: "Spendly",
        tagline: "Track every dollar, effortlessly",
        reasoning: "Simple derivation of 'spend' with a friendly '-ly' suffix. Instantly communicates purpose.",
        brandScore: {
          overall: 84,
          breakdown: { memorability: 88, pronounceability: 94, uniqueness: 70, relevance: 92, length: 86 },
          summary: "Very approachable and clear. The friendly tone fits the freelancer audience well.",
        },
        domains: [
          { domain: "spendly.com", tld: ".com", available: false, checkedAgo: "3h ago" },
          { domain: "spendly.net", tld: ".net", available: true, checkedAgo: "6h ago" },
          { domain: "spendly.app", tld: ".app", available: true, checkedAgo: "1d ago" },
          { domain: "spendly.dev", tld: ".dev", available: true, checkedAgo: "2d ago" },
          { domain: "spendly.io", tld: ".io" },
          { domain: "spendly.ai", tld: ".ai" },
          { domain: "spendly.co", tld: ".co" },
        ],
      },
      {
        name: "Ledgr",
        tagline: "Your freelance ledger, simplified",
        reasoning: "Shortened 'ledger' dropping the 'e' — trendy, tech-savvy, and domain-friendly.",
        brandScore: {
          overall: 81,
          breakdown: { memorability: 84, pronounceability: 76, uniqueness: 86, relevance: 80, length: 90 },
          summary: "Distinctive and brandable. Slight spelling ambiguity but strong character.",
        },
        domains: [
          { domain: "ledgr.com", tld: ".com", available: true, checkedAgo: "2m ago" },
          { domain: "ledgr.net", tld: ".net", available: true, checkedAgo: "5m ago" },
          { domain: "ledgr.app", tld: ".app", available: true, checkedAgo: "12m ago" },
          { domain: "ledgr.dev", tld: ".dev", available: true, checkedAgo: "1h ago" },
          { domain: "ledgr.io", tld: ".io" },
          { domain: "ledgr.ai", tld: ".ai" },
          { domain: "ledgr.co", tld: ".co" },
        ],
      },
      {
        name: "Cashpilot",
        tagline: "Autopilot for your cash flow",
        reasoning: "Combines 'cash' with 'pilot' — implies automated financial oversight for freelancers.",
        brandScore: {
          overall: 80,
          breakdown: { memorability: 82, pronounceability: 88, uniqueness: 74, relevance: 86, length: 72 },
          summary: "Clear value proposition in the name. Slightly long but very descriptive.",
        },
        domains: [
          { domain: "cashpilot.com", tld: ".com", available: false, checkedAgo: "3h ago" },
          { domain: "cashpilot.net", tld: ".net", available: false, checkedAgo: "6h ago" },
          { domain: "cashpilot.app", tld: ".app", available: true, checkedAgo: "1d ago" },
          { domain: "cashpilot.dev", tld: ".dev", available: true, checkedAgo: "2d ago" },
          { domain: "cashpilot.io", tld: ".io" },
          { domain: "cashpilot.ai", tld: ".ai" },
          { domain: "cashpilot.co", tld: ".co" },
        ],
      },
      {
        name: "Receipto",
        tagline: "Every receipt. Every deduction.",
        reasoning: "Playful twist on 'receipt' with an '-o' ending — fun, memorable, and clear.",
        brandScore: {
          overall: 77,
          breakdown: { memorability: 80, pronounceability: 82, uniqueness: 76, relevance: 78, length: 80 },
          summary: "Memorable and lighthearted. Works well for a consumer-facing freelancer tool.",
        },
        domains: [
          { domain: "receipto.com", tld: ".com", available: true, checkedAgo: "2m ago" },
          { domain: "receipto.net", tld: ".net", available: true, checkedAgo: "5m ago" },
          { domain: "receipto.app", tld: ".app", available: true, checkedAgo: "12m ago" },
          { domain: "receipto.dev", tld: ".dev", available: true, checkedAgo: "1h ago" },
          { domain: "receipto.io", tld: ".io" },
          { domain: "receipto.ai", tld: ".ai" },
          { domain: "receipto.co", tld: ".co" },
        ],
      },
      {
        name: "Tallyd",
        tagline: "Keep a running tally of your business",
        reasoning: "From 'tally' with a shortened past tense — implies everything is already tracked.",
        brandScore: {
          overall: 75,
          breakdown: { memorability: 78, pronounceability: 72, uniqueness: 80, relevance: 74, length: 82 },
          summary: "Unique spelling may cause confusion but gives a strong, distinctive brand identity.",
        },
        domains: [
          { domain: "tallyd.com", tld: ".com", available: true, checkedAgo: "3h ago" },
          { domain: "tallyd.net", tld: ".net", available: true, checkedAgo: "6h ago" },
          { domain: "tallyd.app", tld: ".app", available: true, checkedAgo: "1d ago" },
          { domain: "tallyd.dev", tld: ".dev", available: true, checkedAgo: "2d ago" },
          { domain: "tallyd.io", tld: ".io" },
          { domain: "tallyd.ai", tld: ".ai" },
          { domain: "tallyd.co", tld: ".co" },
        ],
      },
    ],
  },
  {
    id: "client-portal",
    input: "Client portal for agencies",
    label: "Client Portal",
    names: [
      {
        name: "Portalo",
        tagline: "Your client hub, wide open",
        reasoning: "Direct play on 'portal' with a friendly Italian-inspired ending. Professional yet approachable.",
        brandScore: {
          overall: 83,
          breakdown: { memorability: 86, pronounceability: 90, uniqueness: 78, relevance: 84, length: 82 },
          summary: "Clean, professional, and easy to remember. Strong agency-market fit.",
        },
        domains: [
          { domain: "portalo.com", tld: ".com", available: false, checkedAgo: "2m ago" },
          { domain: "portalo.net", tld: ".net", available: true, checkedAgo: "5m ago" },
          { domain: "portalo.app", tld: ".app", available: true, checkedAgo: "12m ago" },
          { domain: "portalo.dev", tld: ".dev", available: true, checkedAgo: "1h ago" },
          { domain: "portalo.io", tld: ".io" },
          { domain: "portalo.ai", tld: ".ai" },
          { domain: "portalo.co", tld: ".co" },
        ],
      },
      {
        name: "Cliently",
        tagline: "Client management, done right",
        reasoning: "'Client' + '-ly' suffix — immediately descriptive, warm, and SaaS-friendly.",
        brandScore: {
          overall: 80,
          breakdown: { memorability: 82, pronounceability: 92, uniqueness: 66, relevance: 94, length: 78 },
          summary: "Highly descriptive but common naming pattern. Strong relevance compensates.",
        },
        domains: [
          { domain: "cliently.com", tld: ".com", available: false, checkedAgo: "3h ago" },
          { domain: "cliently.net", tld: ".net", available: true, checkedAgo: "6h ago" },
          { domain: "cliently.app", tld: ".app", available: true, checkedAgo: "1d ago" },
          { domain: "cliently.dev", tld: ".dev", available: true, checkedAgo: "2d ago" },
          { domain: "cliently.io", tld: ".io" },
          { domain: "cliently.ai", tld: ".ai" },
          { domain: "cliently.co", tld: ".co" },
        ],
      },
      {
        name: "Briefcase",
        tagline: "Everything your client needs, in one place",
        reasoning: "Real word evoking professionalism and organization. Instantly understood.",
        brandScore: {
          overall: 86,
          breakdown: { memorability: 90, pronounceability: 96, uniqueness: 68, relevance: 88, length: 76 },
          summary: "Excellent memorability and professional tone. Domain availability may be challenging.",
        },
        domains: [
          { domain: "briefcase.com", tld: ".com", available: false, checkedAgo: "2m ago" },
          { domain: "briefcase.net", tld: ".net", available: false, checkedAgo: "5m ago" },
          { domain: "briefcase.app", tld: ".app", available: true, checkedAgo: "12m ago" },
          { domain: "briefcase.dev", tld: ".dev", available: true, checkedAgo: "1h ago" },
          { domain: "briefcase.io", tld: ".io" },
          { domain: "briefcase.ai", tld: ".ai" },
          { domain: "briefcase.co", tld: ".co" },
        ],
      },
      {
        name: "Hudlr",
        tagline: "Huddle up with your clients",
        reasoning: "From 'huddle' with a modern shortened spelling. Implies collaboration and closeness.",
        brandScore: {
          overall: 74,
          breakdown: { memorability: 76, pronounceability: 68, uniqueness: 82, relevance: 72, length: 84 },
          summary: "Distinctive but the dropped vowel may cause spelling confusion.",
        },
        domains: [
          { domain: "hudlr.com", tld: ".com", available: true, checkedAgo: "3h ago" },
          { domain: "hudlr.net", tld: ".net", available: true, checkedAgo: "6h ago" },
          { domain: "hudlr.app", tld: ".app", available: true, checkedAgo: "1d ago" },
          { domain: "hudlr.dev", tld: ".dev", available: true, checkedAgo: "2d ago" },
          { domain: "hudlr.io", tld: ".io" },
          { domain: "hudlr.ai", tld: ".ai" },
          { domain: "hudlr.co", tld: ".co" },
        ],
      },
      {
        name: "Deliverabl",
        tagline: "Deliver more than expectations",
        reasoning: "Based on 'deliverable' — core agency concept. The shortened spelling is modern and domain-friendly.",
        brandScore: {
          overall: 72,
          breakdown: { memorability: 74, pronounceability: 70, uniqueness: 78, relevance: 80, length: 58 },
          summary: "Strong concept but the truncation makes it harder to spell and slightly long.",
        },
        domains: [
          { domain: "deliverabl.com", tld: ".com", available: true, checkedAgo: "2m ago" },
          { domain: "deliverabl.net", tld: ".net", available: true, checkedAgo: "5m ago" },
          { domain: "deliverabl.app", tld: ".app", available: true, checkedAgo: "12m ago" },
          { domain: "deliverabl.dev", tld: ".dev", available: true, checkedAgo: "1h ago" },
          { domain: "deliverabl.io", tld: ".io" },
          { domain: "deliverabl.ai", tld: ".ai" },
          { domain: "deliverabl.co", tld: ".co" },
        ],
      },
    ],
  },
  {
    id: "habit-tracker",
    input: "Habit tracker with AI coaching",
    label: "AI Habit Tracker",
    names: [
      {
        name: "Habitra",
        tagline: "Build habits that actually stick",
        reasoning: "Blend of 'habit' with a modern suffix — sounds like a personal assistant for habits.",
        brandScore: {
          overall: 86,
          breakdown: { memorability: 88, pronounceability: 90, uniqueness: 82, relevance: 86, length: 86 },
          summary: "Strong, distinctive, and immediately category-relevant. Great startup name.",
        },
        domains: [
          { domain: "habitra.com", tld: ".com", available: true, checkedAgo: "3h ago" },
          { domain: "habitra.net", tld: ".net", available: true, checkedAgo: "6h ago" },
          { domain: "habitra.app", tld: ".app", available: true, checkedAgo: "1d ago" },
          { domain: "habitra.dev", tld: ".dev", available: true, checkedAgo: "2d ago" },
          { domain: "habitra.io", tld: ".io" },
          { domain: "habitra.ai", tld: ".ai" },
          { domain: "habitra.co", tld: ".co" },
        ],
      },
      {
        name: "Nudgekit",
        tagline: "Gentle nudges, real results",
        reasoning: "Combines 'nudge' (behavioral science term) with 'kit' — implies a toolkit of gentle reminders.",
        brandScore: {
          overall: 81,
          breakdown: { memorability: 84, pronounceability: 86, uniqueness: 80, relevance: 78, length: 76 },
          summary: "Clever reference to behavioral science. Approachable and memorable.",
        },
        domains: [
          { domain: "nudgekit.com", tld: ".com", available: true, checkedAgo: "2m ago" },
          { domain: "nudgekit.net", tld: ".net", available: true, checkedAgo: "5m ago" },
          { domain: "nudgekit.app", tld: ".app", available: true, checkedAgo: "12m ago" },
          { domain: "nudgekit.dev", tld: ".dev", available: true, checkedAgo: "1h ago" },
          { domain: "nudgekit.io", tld: ".io" },
          { domain: "nudgekit.ai", tld: ".ai" },
          { domain: "nudgekit.co", tld: ".co" },
        ],
      },
      {
        name: "Routinr",
        tagline: "Your AI-powered daily routine",
        reasoning: "'Routine' with dropped 'e' — trendy spelling that implies structured daily habits.",
        brandScore: {
          overall: 79,
          breakdown: { memorability: 80, pronounceability: 74, uniqueness: 78, relevance: 88, length: 82 },
          summary: "Very relevant but the missing vowel might cause confusion. Strong concept.",
        },
        domains: [
          { domain: "routinr.com", tld: ".com", available: true, checkedAgo: "3h ago" },
          { domain: "routinr.net", tld: ".net", available: true, checkedAgo: "6h ago" },
          { domain: "routinr.app", tld: ".app", available: true, checkedAgo: "1d ago" },
          { domain: "routinr.dev", tld: ".dev", available: true, checkedAgo: "2d ago" },
          { domain: "routinr.io", tld: ".io" },
          { domain: "routinr.ai", tld: ".ai" },
          { domain: "routinr.co", tld: ".co" },
        ],
      },
      {
        name: "Streakly",
        tagline: "Keep your streak alive",
        reasoning: "Based on 'streak' — the gamification element that drives habit app engagement.",
        brandScore: {
          overall: 83,
          breakdown: { memorability: 86, pronounceability: 90, uniqueness: 74, relevance: 84, length: 80 },
          summary: "Taps into the streak mechanic that users love. Clear and motivating.",
        },
        domains: [
          { domain: "streakly.com", tld: ".com", available: true, checkedAgo: "2m ago" },
          { domain: "streakly.net", tld: ".net", available: true, checkedAgo: "5m ago" },
          { domain: "streakly.app", tld: ".app", available: true, checkedAgo: "12m ago" },
          { domain: "streakly.dev", tld: ".dev", available: true, checkedAgo: "1h ago" },
          { domain: "streakly.io", tld: ".io" },
          { domain: "streakly.ai", tld: ".ai" },
          { domain: "streakly.co", tld: ".co" },
        ],
      },
      {
        name: "Coachbit",
        tagline: "Tiny coaching, big changes",
        reasoning: "'Coach' + 'bit' — implies bite-sized AI coaching moments throughout the day.",
        brandScore: {
          overall: 78,
          breakdown: { memorability: 80, pronounceability: 84, uniqueness: 76, relevance: 82, length: 76 },
          summary: "Solid compound name that communicates both the AI coaching and micro-habit angle.",
        },
        domains: [
          { domain: "coachbit.com", tld: ".com", available: true, checkedAgo: "3h ago" },
          { domain: "coachbit.net", tld: ".net", available: true, checkedAgo: "6h ago" },
          { domain: "coachbit.app", tld: ".app", available: true, checkedAgo: "1d ago" },
          { domain: "coachbit.dev", tld: ".dev", available: true, checkedAgo: "2d ago" },
          { domain: "coachbit.io", tld: ".io" },
          { domain: "coachbit.ai", tld: ".ai" },
          { domain: "coachbit.co", tld: ".co" },
        ],
      },
    ],
  },
  {
    id: "invoice-generator",
    input: "Invoice generator for contractors",
    label: "Invoice Generator",
    names: [
      {
        name: "Invoiceflow",
        tagline: "Invoices that flow, payments that follow",
        reasoning: "Pairs 'invoice' with 'flow' — suggests smooth, automated invoicing workflows.",
        brandScore: {
          overall: 82,
          breakdown: { memorability: 80, pronounceability: 88, uniqueness: 72, relevance: 94, length: 68 },
          summary: "Highly descriptive and clear. Slightly long but communicates value instantly.",
        },
        domains: [
          { domain: "invoiceflow.com", tld: ".com", available: false, checkedAgo: "2m ago" },
          { domain: "invoiceflow.net", tld: ".net", available: false, checkedAgo: "5m ago" },
          { domain: "invoiceflow.app", tld: ".app", available: true, checkedAgo: "12m ago" },
          { domain: "invoiceflow.dev", tld: ".dev", available: true, checkedAgo: "1h ago" },
          { domain: "invoiceflow.io", tld: ".io" },
          { domain: "invoiceflow.ai", tld: ".ai" },
          { domain: "invoiceflow.co", tld: ".co" },
        ],
      },
      {
        name: "Billforge",
        tagline: "Forge professional invoices in seconds",
        reasoning: "'Bill' + 'forge' — implies crafting/building invoices with strength and precision.",
        brandScore: {
          overall: 85,
          breakdown: { memorability: 88, pronounceability: 90, uniqueness: 82, relevance: 80, length: 84 },
          summary: "Strong, professional, and distinctive. Good balance of descriptive and brandable.",
        },
        domains: [
          { domain: "billforge.com", tld: ".com", available: true, checkedAgo: "3h ago" },
          { domain: "billforge.net", tld: ".net", available: true, checkedAgo: "6h ago" },
          { domain: "billforge.app", tld: ".app", available: true, checkedAgo: "1d ago" },
          { domain: "billforge.dev", tld: ".dev", available: true, checkedAgo: "2d ago" },
          { domain: "billforge.io", tld: ".io" },
          { domain: "billforge.ai", tld: ".ai" },
          { domain: "billforge.co", tld: ".co" },
        ],
      },
      {
        name: "Paypulse",
        tagline: "Keep your payments on pulse",
        reasoning: "'Pay' + 'pulse' — implies real-time tracking of payment status.",
        brandScore: {
          overall: 80,
          breakdown: { memorability: 84, pronounceability: 86, uniqueness: 74, relevance: 78, length: 80 },
          summary: "Catchy alliteration gives it good recall. Slightly ambiguous purpose.",
        },
        domains: [
          { domain: "paypulse.com", tld: ".com", available: false, checkedAgo: "2m ago" },
          { domain: "paypulse.net", tld: ".net", available: true, checkedAgo: "5m ago" },
          { domain: "paypulse.app", tld: ".app", available: true, checkedAgo: "12m ago" },
          { domain: "paypulse.dev", tld: ".dev", available: true, checkedAgo: "1h ago" },
          { domain: "paypulse.io", tld: ".io" },
          { domain: "paypulse.ai", tld: ".ai" },
          { domain: "paypulse.co", tld: ".co" },
        ],
      },
      {
        name: "Sendbill",
        tagline: "Create. Send. Get paid.",
        reasoning: "Direct action-oriented compound — says exactly what it does.",
        brandScore: {
          overall: 77,
          breakdown: { memorability: 78, pronounceability: 92, uniqueness: 64, relevance: 90, length: 82 },
          summary: "Extremely clear but generic. Works well as a utility brand.",
        },
        domains: [
          { domain: "sendbill.com", tld: ".com", available: true, checkedAgo: "3h ago" },
          { domain: "sendbill.net", tld: ".net", available: true, checkedAgo: "6h ago" },
          { domain: "sendbill.app", tld: ".app", available: true, checkedAgo: "1d ago" },
          { domain: "sendbill.dev", tld: ".dev", available: true, checkedAgo: "2d ago" },
          { domain: "sendbill.io", tld: ".io" },
          { domain: "sendbill.ai", tld: ".ai" },
          { domain: "sendbill.co", tld: ".co" },
        ],
      },
      {
        name: "Notchpay",
        tagline: "Notch up your invoicing game",
        reasoning: "'Notch' implies quality and precision; 'pay' grounds it in payments.",
        brandScore: {
          overall: 74,
          breakdown: { memorability: 76, pronounceability: 80, uniqueness: 78, relevance: 72, length: 76 },
          summary: "Distinctive but the connection to invoicing isn't immediately obvious.",
        },
        domains: [
          { domain: "notchpay.com", tld: ".com", available: true, checkedAgo: "2m ago" },
          { domain: "notchpay.net", tld: ".net", available: true, checkedAgo: "5m ago" },
          { domain: "notchpay.app", tld: ".app", available: true, checkedAgo: "12m ago" },
          { domain: "notchpay.dev", tld: ".dev", available: true, checkedAgo: "1h ago" },
          { domain: "notchpay.io", tld: ".io" },
          { domain: "notchpay.ai", tld: ".ai" },
          { domain: "notchpay.co", tld: ".co" },
        ],
      },
    ],
  },
  {
    id: "seo-audit",
    input: "SEO audit tool for small businesses",
    label: "SEO Audit Tool",
    names: [
      {
        name: "Rankpilot",
        tagline: "Navigate your way to page one",
        reasoning: "'Rank' (search rankings) + 'pilot' (guidance) — implies expert SEO navigation.",
        brandScore: {
          overall: 84,
          breakdown: { memorability: 86, pronounceability: 88, uniqueness: 78, relevance: 88, length: 78 },
          summary: "Strong metaphor that resonates with the target audience. Professional and clear.",
        },
        domains: [
          { domain: "rankpilot.com", tld: ".com", available: false, checkedAgo: "3h ago" },
          { domain: "rankpilot.net", tld: ".net", available: false, checkedAgo: "6h ago" },
          { domain: "rankpilot.app", tld: ".app", available: true, checkedAgo: "1d ago" },
          { domain: "rankpilot.dev", tld: ".dev", available: true, checkedAgo: "2d ago" },
          { domain: "rankpilot.io", tld: ".io" },
          { domain: "rankpilot.ai", tld: ".ai" },
          { domain: "rankpilot.co", tld: ".co" },
        ],
      },
      {
        name: "Sitescore",
        tagline: "Know your site's real score",
        reasoning: "'Site' + 'score' — directly communicates the audit/scoring function.",
        brandScore: {
          overall: 81,
          breakdown: { memorability: 82, pronounceability: 92, uniqueness: 68, relevance: 92, length: 76 },
          summary: "Extremely clear purpose. May face competition from similar names but highly relevant.",
        },
        domains: [
          { domain: "sitescore.com", tld: ".com", available: false, checkedAgo: "2m ago" },
          { domain: "sitescore.net", tld: ".net", available: true, checkedAgo: "5m ago" },
          { domain: "sitescore.app", tld: ".app", available: true, checkedAgo: "12m ago" },
          { domain: "sitescore.dev", tld: ".dev", available: true, checkedAgo: "1h ago" },
          { domain: "sitescore.io", tld: ".io" },
          { domain: "sitescore.ai", tld: ".ai" },
          { domain: "sitescore.co", tld: ".co" },
        ],
      },
      {
        name: "Crawlr",
        tagline: "Deep-crawl your site in seconds",
        reasoning: "From 'crawler' (web crawler) with trendy shortened spelling. Technical credibility.",
        brandScore: {
          overall: 79,
          breakdown: { memorability: 82, pronounceability: 74, uniqueness: 80, relevance: 82, length: 86 },
          summary: "Technical and niche. Appeals to the developer-adjacent audience perfectly.",
        },
        domains: [
          { domain: "crawlr.com", tld: ".com", available: false, checkedAgo: "3h ago" },
          { domain: "crawlr.net", tld: ".net", available: true, checkedAgo: "6h ago" },
          { domain: "crawlr.app", tld: ".app", available: true, checkedAgo: "1d ago" },
          { domain: "crawlr.dev", tld: ".dev", available: true, checkedAgo: "2d ago" },
          { domain: "crawlr.io", tld: ".io" },
          { domain: "crawlr.ai", tld: ".ai" },
          { domain: "crawlr.co", tld: ".co" },
        ],
      },
      {
        name: "Indexly",
        tagline: "Get indexed. Get found.",
        reasoning: "From 'index' (Google indexing) with '-ly' suffix. Friendly and SEO-specific.",
        brandScore: {
          overall: 78,
          breakdown: { memorability: 80, pronounceability: 88, uniqueness: 70, relevance: 80, length: 82 },
          summary: "Clear SEO connection and easy to say. The -ly pattern is common in SaaS.",
        },
        domains: [
          { domain: "indexly.com", tld: ".com", available: false, checkedAgo: "2m ago" },
          { domain: "indexly.net", tld: ".net", available: true, checkedAgo: "5m ago" },
          { domain: "indexly.app", tld: ".app", available: true, checkedAgo: "12m ago" },
          { domain: "indexly.dev", tld: ".dev", available: true, checkedAgo: "1h ago" },
          { domain: "indexly.io", tld: ".io" },
          { domain: "indexly.ai", tld: ".ai" },
          { domain: "indexly.co", tld: ".co" },
        ],
      },
      {
        name: "Serpwise",
        tagline: "SERP-smart decisions for your business",
        reasoning: "'SERP' (Search Engine Results Page) + 'wise' — for founders who know SEO matters.",
        brandScore: {
          overall: 76,
          breakdown: { memorability: 74, pronounceability: 78, uniqueness: 82, relevance: 84, length: 80 },
          summary: "Niche and insider-y. Strong for an audience that understands SERP terminology.",
        },
        domains: [
          { domain: "serpwise.com", tld: ".com", available: true, checkedAgo: "3h ago" },
          { domain: "serpwise.net", tld: ".net", available: true, checkedAgo: "6h ago" },
          { domain: "serpwise.app", tld: ".app", available: true, checkedAgo: "1d ago" },
          { domain: "serpwise.dev", tld: ".dev", available: true, checkedAgo: "2d ago" },
          { domain: "serpwise.io", tld: ".io" },
          { domain: "serpwise.ai", tld: ".ai" },
          { domain: "serpwise.co", tld: ".co" },
        ],
      },
    ],
  },
];
